---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-dev-env
spec:
  generators:
  - list:
      elements:
      - namespace: de
      - namespace: te
  template:
    metadata:
      name: "{{ namespace }}-my-app"
    spec:
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations
        namespace: '{{namespace}}'                # default cluster is used, other cluster can be specified here
      project: default                                          # argocd project
      source:
        repoURL: https://github.com/geksogen/argocd-node-app-config.git
        targetRevision: HEAD
        path: node-app